// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBB3fi-BXhWmSnZbT8DI_40iGSjFwXSWaA',
    appId: '1:242280840990:web:8f15fdc07eaa39a44e930f',
    messagingSenderId: '242280840990',
    projectId: 'mushiyabeauty',
    authDomain: 'mushiyabeauty.firebaseapp.com',
    storageBucket: 'mushiyabeauty.firebasestorage.app',
    measurementId: 'G-1TQPHH329Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIl4OADNhAlx0GKN5hhuxxWUrAaknUrfE',
    appId: '1:242280840990:android:8ff8484bbdcb49ad4e930f',
    messagingSenderId: '242280840990',
    projectId: 'mushiyabeauty',
    storageBucket: 'mushiyabeauty.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4BvgVUhFMlbkjWRCM07vXHU4avpMNllQ',
    appId: '1:242280840990:ios:1996ec6008da15a14e930f',
    messagingSenderId: '242280840990',
    projectId: 'mushiyabeauty',
    storageBucket: 'mushiyabeauty.firebasestorage.app',
    androidClientId: '242280840990-b5qlb764seb9q01f3ugn2b9p69dsgp4v.apps.googleusercontent.com',
    iosClientId: '242280840990-54inrvfrv18n387bq7g6scs0phmold0p.apps.googleusercontent.com',
    iosBundleId: 'com.ahad.mushiyabeauty.mushiyaBeauty',
  );

}